import type {Metadata} from "next";
import "./globals.css";

import {ThemeProvider} from "@/components/core/theme/theme-provider";
import {Navbar} from "@/components/core/navbar";
import {Footer} from "@/components/core/footer";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Navbar/>
            <div className="xl:px-64 md:px-16 px-4 select-none">
                {children}
            </div>
            <Footer/>
        </ThemeProvider>
        </body>
        </html>
    );
}
